name: build-test-disk
on:
  workflow_dispatch:
    inputs:
      format:
        description: 'Format'
        default: 'd64'
        required: true
        type: choice
        options:
          - d64
          - d71

jobs:
  builddisk:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Print selected format
          run: 'echo "Selected Format: ${{ inputs.format }}"'

        - name: install ubuntu packages
          uses: awalsh128/cache-apt-pkgs-action@latest
          with:
            packages: acme vice
            version: 1.0

        - name: Print hexdump Version
          run: 'hexdump -V'

        - name: Print acme Version
          run: 'acme -V'

        - name: Print python Version
          run: 'python3 -V'

        - name: Print c1541 Version
          run: 'c1541 -version'

        - name: Create empty disk image and show dir
          run: |
           c1541 -format "dmon128,6b" ${{ inputs.format }} dmon128.${{ inputs.format }} 8
           c1541 dmon128.${{ inputs.format }} -dir
           c1541 dmon128.${{ inputs.format }} -block 18 0
